<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE class [
  <!ELEMENT class (family)*>
   <!ELEMENT family (hobby,age,gender,position,name)>
   <!ELEMENT hobby (#PCDATA)>
   <!ELEMENT age (#PCDATA)>
   <!ELEMENT gender (#PCDATA)>
   <!ELEMENT position (#PCDATA)>
   <!ELEMENT name (#PCDATA)>
        ]>
<class>
    <family>
        <hobby>Dancing</hobby>
        <age>40</age>
        <gender>female</gender>
        <position>daughter</position>
        <name>Erioluwa</name>
    </family>
    <family>
        <hobby>Singing</hobby>
        <age>11</age>
        <gender>female</gender>
        <position>grand-daughter</position>
        <name>Ireoluwa</name>
    </family>
    <family>
        <hobby>Eating</hobby>
        <age>1</age>
        <gender>female</gender>
        <position>pet</position>
        <name>Bella</name>
    </family>
    <family>
        <hobby>Working</hobby>
        <age>20</age>
        <gender>male</gender>
        <position>Son</position>
        <name>Dotun</name>
    </family>
    <family>
        <hobby>cooking</hobby>
        <age>50</age>
        <gender>female</gender>
        <position>mother</position>
        <name>Mrs Seun</name>
    </family>
    <family>
        <hobby>Reading</hobby>
        <age>55</age>
        <gender>male</gender>
        <position>Father</position>
        <name>MR Samson</name>
    </family>
<!--    <family hobby="Dancing" age="20" gender="female" position="daughter">Erioluwa</family>-->
<!--    <family hobby="singing" age="10" gender="female" position="grand-daughter">Ireoluwa</family>-->
<!--    <family hobby="eating" age="1" gender="female" position="pet">Bella</family>-->
<!--    <family hobby="working" age="40" gender="male" position="son">Dotun</family>-->
<!--    <family hobby="cooking" age="50" gender="female" position="mother">Mrs Seun</family>-->
<!--    <family hobby="Reading" age="55" gender="male" position="father">Ireoluwa</family>-->

</class>


